/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaAlgorithms;

import JavaAlgorithms.datastructures.MyLinkedList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        MyLinkedList list = new MyLinkedList();
        list.add(1);
        list.add(2);
        list.add(3);

        for (int i=0; i<list.size(); i++) {
            System.out.println(list.remove());
        }
    }
}
